### ISSUE TITLE
Match metadata titles to Commerce 

### ISSUE THREAD

**Issue by meker12** [ankumalh/assets-commerce#3]
@ankumalh  A couple suggestions to improve the metadata form in the boilerplate repo to have parity with existing Commerce image management:

Suggestion 1:

- Update the [values for the roles](https://github.com/ankumalh/assets-commerce/blob/8dde8df3dca2273bd17d7ae22ccc3efa6be49a4d/ui.apps/src/main/content/jcr_root/apps/commerce/ui/components/productdata/render.jsp#L134) to match the names in Adobe Commerce?   -  thumbnail, base_image, swatch, small_image 

(Commerce doc reference [Image roles](https://experienceleague.adobe.com/en/docs/commerce-admin/catalog/products/digital-assets/product-image#image-roles))
 
 Suggestion 2:

- Add labels for position and roles field in the metadata form: 

![image](https://github.com/user-attachments/assets/1f36099c-3730-499b-9c9e-a83d46851bde)

The role isn't too bad since it says:  "[Choose usage for image](https://github.com/ankumalh/assets-commerce/blob/8dde8df3dca2273bd17d7ae22ccc3efa6be49a4d/ui.apps/src/main/content/jcr_root/apps/commerce/ui/components/productdata/render.jsp#L171)"  -- but text might be better to say "Select role for image usage"

**Comment by ankumalh** [comment]
@meker12 - Pablo took care of 1 a while back with https://github.com/ankumalh/assets-commerce/commit/f693023aacd2e404edb285941996f0b627996161

the image in ReadMe needs to be updated though
