### ISSUE TITLE
Replace `aemclouddemo` by `aemassetintegration`

### ISSUE THREAD

**Issue by meker12** [ankumalh/assets-commerce#4]
Since this project is to support the AEM Asset integration for Commerce, it makes sense to replace the identifier `aemclouddemo`.  with `aemassetintegration`.  Pablo added this customization to the code deployed to the [test instance](https://experience.adobe.com/#/@commercedecepticons/cloud-manager/home.html/program/137303).

If you make the change in the source repo, then customers won't have to change it.

**Comment by meker12** [comment]
@pablomoreno61 addressed this issue in PR #2

**Comment by pablomoreno61** [comment]
@ankumalh I don't know if we can use aemassetintegration keyword or if each merchant must use their own identifier. In the PR https://github.com/ankumalh/assets-commerce/pull/2 I mostly changed `com.aemclouddemo.commerce` by `com.<my-app>.commerce`.

- Could the merchants use any combination of 3 dotted words?
- Could all the merchants repeat this `com.aemassetintegration.commerce` or will it conflict if it already exists?
